name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: project-documentation

      - name: Build and Deploy website
        run: GIT_USER=$DEPLOYMENT_AUTHOR yarn deploy
        working-directory: project-documentation
